# Generated by Django 5.2.1 on 2025-06-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('color_identificacion', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo de Lugar',
                'verbose_name_plural': 'Tipos de Lugares',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('piso', models.CharField(default='1', max_length=10)),
                ('seccion', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('RESERVADO', 'Reservado')], default='DISPONIBLE', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('tiene_techo', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.tipolugar')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['numero'],
            },
        ),
    ]
