# Generated by Django 5.2.1 on 2025-06-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='disponible',
        ),
        migrations.AddField(
            model_name='lugar',
            name='ancho_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='bloque',
            field=models.CharField(blank=True, help_text='Ej: Bloque 1, Edificio Principal', max_length=20),
        ),
        migrations.AddField(
            model_name='lugar',
            name='es_accesible',
            field=models.BooleanField(default=True, help_text='Accesible para personas con discapacidad'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='largo_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='capacidad_maxima',
            field=models.IntegerField(default=0, help_text='0 = sin límite'),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='categoria_usuario_permitida',
            field=models.CharField(choices=[('TODOS', 'Todos los usuarios'), ('ESTUDIANTE', 'Solo Estudiantes'), ('PROFESOR', 'Solo Profesores'), ('PERSONAL', 'Solo Personal Administrativo'), ('LIMPIEZA', 'Solo Personal de Limpieza'), ('VISITANTE', 'Solo Visitantes'), ('ACADEMICO', 'Estudiantes y Profesores'), ('INTERNO', 'Personal Interno (No visitantes)')], default='TODOS', help_text='Qué categorías de usuarios pueden usar este tipo de lugar', max_length=20),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='icono',
            field=models.CharField(default='🅿️', help_text='Emoji o icono para mostrar', max_length=50),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='requiere_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='tarifa_estudiante',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa especial para estudiantes (0 = usar tarifa normal)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='tiempo_maximo_minutos',
            field=models.IntegerField(default=0, help_text='Tiempo máximo de estacionamiento en minutos (0 = sin límite)'),
        ),
        migrations.AddField(
            model_name='tipolugar',
            name='tipo_vehiculo_permitido',
            field=models.CharField(choices=[('TODOS', 'Todos los vehículos'), ('AUTO', 'Solo Automóviles'), ('MOTO', 'Solo Motocicletas'), ('CAMIONETA', 'Solo Camionetas'), ('BICICLETA', 'Solo Bicicletas'), ('MOTOR', 'Vehículos a motor (Auto, Moto, Camioneta)')], default='TODOS', help_text='Qué tipos de vehículos pueden usar este lugar', max_length=20),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='seccion',
            field=models.CharField(blank=True, help_text='Ej: A, B, Norte, Sur', max_length=20),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='lugares.tipolugar'),
        ),
    ]
