# Generated by Django 5.2.1 on 2025-06-05 01:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EN_CURSO', max_length=20)),
                ('tarifa_aplicada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Crédito Institucional'), ('GRATIS', 'Gratuito')], default='EFECTIVO', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ticket_numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='lugares.lugar')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_realizados', to='usuarios.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Ingreso de Vehículo',
                'verbose_name_plural': 'Ingresos de Vehículos',
                'ordering': ['-hora_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ReporteEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('total_estacionamientos', models.IntegerField(default=0)),
                ('total_tiempo_minutos', models.IntegerField(default=0)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vehiculos_utilizados', models.JSONField(default=list)),
                ('lugares_utilizados', models.JSONField(default=list)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Reporte de Estacionamiento',
                'verbose_name_plural': 'Reportes de Estacionamiento',
            },
        ),
    ]
